### PR TITLE
Fix and harden url encoding

### LINKED ISSUE #56: HttpUrl path is correctly encoded
HttpUrl implements a custom path encoding mechanism which does not properly escape the path. Refactor HttpUrl and harden it using rawurlencode() instead of a urlencode() or custom path encoding.

Note: since PHP5.3 rawurlencode comforms to [rfc3986](http://www.faqs.org/rfcs/rfc3986.html). ([more info](http://stackoverflow.com/questions/996139/urlencode-vs-rawurlencode))

### PR DESCRIPTION
**Pull request by johanjanssens**
resolve #56

### CODE REVIEW

**Comment by johanjanssens** [comment]
@ercanozkaya Can you review this. This fix should also be merged to Joomlatools Framework 2.x, will need more additional testing, might best added to a feature release.

File: code/http/url/url.php [hunk 1]
```diff
@@ -387,14 +382,14 @@ public function setPath($path)
         if (is_string($path))
         {
             if (!empty($path)) {
-                $path = explode('/', $path);
+                $path = explode('/', trim($path, '/'));
```
Comment (ercanozkaya) [inline code/http/url/url.php]: @johanjanssens A trim might not be a good idea here. You cannot set the path to foo/bar/ with a trailing slash.

File: code/http/url/url.php [hunk 2]
```diff
@@ -612,18 +624,18 @@ public function toString($parts = self::FULL, $escape = null)
             //Add the username and password
             if (($parts & self::USER) && !empty($this->user))
             {
-                $url .= urlencode($this->user);
+                $url .= rawurlencode($this->user);
```
Comment (oligriffiths) [inline code/http/url/url.php]: This could be double encoding the user.
Is there any way to set `$this->user` outside of the `setUser()` method? If not, then the `rawurlencode()` isn't needed.

File: code/http/url/url.php (hunk 1 above)
Comment (johanjanssens) [inline code/http/url/url.php]: Changed to using an ltrim instead of trim() this should solve it.

File: code/http/url/url.php (hunk 2 above)
Comment (johanjanssens) [inline code/http/url/url.php]: @oligriffiths User is always set through setUser() which decoded on input and to be safe we encode on output to string. I don't see how that could lead to double encoding?

File: code/http/url/url.php [hunk 3]
```diff
@@ -356,20 +343,28 @@ public function getPort()
...
 
     /**
      * Returns the path portion as a string or array
      *
-     * @param     boolean $toArray If TRUE return an array. Default FALSE
+     * This method will encode the path to conform to RFC 3986 returned as string.
+     * @link https://tools.ietf.org/html/rfc3986
+     *
+     * @param   boolean $toArray If TRUE return an array. Default FALSE
      * @return  string|array The path string; e.g., `path/to/site`.
```
Comment (ercanozkaya) [inline code/http/url/url.php]: @johanjanssens need to update the phpdoc to /path/to/site as there will always be a leading slash now.

Comment (johanjanssens) [inline code/http/url/url.php]: Fixed
